# Site settings
title: Sheng Li | Love Work and Enjoy Life
description: "Placing things where they should be"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "li-sheng.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sheng Li
user_description: I'm a former content producer and a new CS graduate from Georgia Tech.
user_title: Content Producer/Software Developer
email: lisheng0316@gmail.com
# twitter_username: lorem_ipsum
github_username:  lisheng0316
linkedin_username: sheng1i
instagram_username: angelorghost

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme:
